version: "3.7"
services:
  api:
    build:
      context: .
    environment:
      - PORT=13333
      - GO_ENV=development
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
    ports:
      - "13333:13333"
    volumes:
      - "./:/app"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"